### ISSUE TITLE
Dashboard loading problem

### ISSUE THREAD

**Issue by milanchheta** [airavata-courses/pika-pika#62]
<img width="1243" alt="Screen Shot 2020-03-20 at 10 02 26 PM" src="https://user-images.githubusercontent.com/30660458/77217163-b0dd1780-6af6-11ea-94db-3d438d6eaf7f.png">

Tried to access the services from frontend but the dashboard does not load anything, might be because of SSL certificate problem.

**Comment by pokearu** [comment]
https://github.com/airavata-courses/pika-pika/commit/45a592d35c53439ddeab0e8b3e65597f96ff85a5

Temporary fix has been made. The permanent fix would be adding SSL. We are looking into it.
